function get_ZB23(N::Integer = 1,
                  tmin = -3.5e6,
                  tmax = 0)
    # these are properties of the solutions
    tend = -3.5e6
    tres = -0.4

    if N > 64 || N < 1
        @error "N should be between 1 and 64."
    end
    skp = convert(Int, floor(tmax / tres))
    ftskp = convert(Int, floor(tend / tres - tmin / tres))

    base_url = "http://www.soest.hawaii.edu/oceanography/faculty/zeebe_files/Astro/"

    number = lpad(N, 2,'0')
    astronomical_solution = "ZB23.R$(number)"
    @info astronomical_solution

    outfile = "out/$(astronomical_solution)_$(tmin)-$(tmax).arrow"
    if isfile(outfile)
        @info "loading file from cache"
        return Arrow.Table(outfile) |> DataFrame
    end

    # # see if we can reuse a bigger one?
    # fls = readdir("out")
    # my_parse = function(x)
    #     if isnothing(x.captures)
    #         return nothing
    #     else
    #         parse(Float64, x.captures)
    #     end
    # end

    # mins = my_parse.(match.(r"_(-[0-9.e]+)", fls))
    # maxs = parse.(Float64, map(x -> x.captures, match.(r"--([0-9e.]+).arrow", fls)))
    # rx = astronomical_solution * r"_-[0-9.e]+--[-0-9.e]+.arrow$"
    # mtch = match.(rx, fls)
    # for (i, fl) in enumerate(fls)
    #     if isnothing(mtch[i])
    #         break
    #     else
    #         rx2 = "_-[0-9.e]+"
    #         fl

    url = "$(base_url)3.5Gyr/ZB23-N64-eiop/$(astronomical_solution).eiop.dat.zip"

    dwn = download(url)
    @info "downloaded"
    unz = ZipFile.Reader(dwn)
    @info "unzipped"

    cols = [
        "time", # time in kyr, negative
        "ecc", # eccentricity
        "inc", # inclination
        "epl", # obliquity
        "cp" # climatic precession e*sin(omegabar)
    ]
    dat = CSV.File(unz.files[1];
                   header = cols,
                   comment = "%",
                   ignorerepeated = true,
                   delim = " ",
                   skipto = skp, footerskip = ftskp,
                   stripwhitespace = true) |>
                       DataFrame
    @info "read"
    if tmin != tend && tmax != 0
        @info "subset"
    end

    rm(dwn)
    @info "removed file"

    dat.sol .= astronomical_solution
    @info "added name"

    Arrow.write(outfile, dat)
    @info "saved Arrow"

    return dat
end

Milankovitch_targets = Dict(
    "p1" => (0.0653, 0.07),
    "p2" => (0.075, 0.0785),
    "p" => (0.065, 0.0785),
    "o1" => (0.0415, 0.044),
    "o2" => (0.0472, 0.0505),
    "o12" => (0.042, 0.0505),
    "o3" => (0.057, 0.0594),
    "e" => (1/155, 1/75),
    "E" => (1/440, 1/370)
)


# generated by DeepSeek to replace astrochron::bandpass
# then improved by myself
# it pads with 0
function bandpass(data::Vector{Float64}, dt::Float64, flow::Float64, fhigh::Float64; filter_order::Int=4, pad_fac::Int=2)
    """
    Apply a bandpass filter to a time series.

    Parameters:
    - data: The input time series (Vector{Float64}).
    - dt: Sampling interval (in kyr).
    - flow: Lower cutoff frequency (in 1/kyr).
    - fhigh: Upper cutoff frequency (in 1/kyr).
    - filter_order: Order of the filter (default is 4).
    - pad_fac: Number of points to pad at the start and end (default is 2).

    Returns:
    - filtered_data: The bandpass-filtered time series.
    """
    # - pad_length: Number of points to pad at the start and end (default is 100).

    # Calculate sampling frequency
    fs = 1.0 / dt  # Sampling frequency in 1/kyr

    # Normalize frequencies to the Nyquist frequency (fs/2)
    nyquist = fs / 2
    f_norm_low = flow / nyquist
    f_norm_high = fhigh / nyquist

    # Design a Butterworth bandpass filter
    bandpass_filter = Butterworth(filter_order)
    bandpass = Bandpass(f_norm_low, f_norm_high)

    # Create the digital filter
    filt = digitalfilter(bandpass, bandpass_filter)

    # Pad the signal
    pad_length = length(data) * pad_fac
    # I tested that:
    # with zeros the output is visually very similar
    # to astrochron::bandpass(window = 0) (rectangular)
    data_padded = vcat(#reverse(data[1:pad_length]),
                       zeros(pad_length),
                       data,
                       # reverse(data[end-pad_length+1:end])
                       zeros(pad_length)
                       )

    # Apply the filter using zero-phase filtering
    filtered_padded = filtfilt(filt, data_padded)

    # Remove the padding
    filtered_data = filtered_padded[pad_length+1:end-pad_length]

    return filtered_data
end

# bootstrapping in 5 non-overlapping chunks
"simple block bootstrap"
my_boot = function(x, fun = mean; b = 69, N = 999)
    n = length(x)
    nblocks = convert(Int, floor(n/b))
    @show nblocks

    megaboot = zeros(N * nblocks)
    # srt = rand(1:nblocks,nblocks)

    cache = zeros(N)
    for i in 1:nblocks # all blocks
        idxmin = (i-1)*b+1
        idxmax = (i-1)*b+b
        cache .= bootstrap(fun,
                           # subset data to rolling blocks of size b
                           x[idxmin:idxmax],
                           BasicSampling(N)).t1 |>
                               Iterators.flatten |>
                               collect
        megaboot[(i-1)*N+1:i*N] .= cache
    end
    return megaboot
end


# bootstrapping for time series
moving_block_bootstrap = function(x, fun = mean; b = 69, N = 999)
    # I did N = 10_000 first but the paper mentions 999, say

    n = length(x)
    rolling_blocks = n - b + 1 # not +1 b/c julia is 1-indexed

    nblocks = convert(Int, floor(n/b))
    @show nblocks # should be about 5
    # pick nblocks at random
    ss = rand(1:rolling_blocks, nblocks)
    # draw n/b of the blocks, with replacement
    idx = [ s .+ collect(1:b) for s in ss ] |> Iterators.flatten |> collect
    # Then aligning these n/b blocks in the order they were picked, will give the bootstrap observations.
    boot_obs = x[idx]
    boot = bootstrap(mean, boot_obs, BasicSampling(N))
    # megaboot = zeros(N * nblocks)
    # cache = zeros(N)
    # for i in 1:rolling_blocks
    #     cache .= bootstrap(fun,
    #                        # subset data to rolling blocks of size b
    #                        boots[i:(i+b-1)],
    #                        MaximumEntropySampling(N)).t1 |>
    #                            Iterators.flatten |>
    #                            collect
    #     megaboot[(i-1)*N+1:i*N] .= cache
    # end
    return boot.t1 |> Iterators.flatten |> collect
end

"gets the ZB23.RXX solution between tmin and tmax, extracts parameter, finds peaks, calculates differences"
my_very_simple_wrapper = function(solution = 1, tmin = -1205e3, tmax = -1200e3;
                                  b = 75, N = 999, parameter = "cp")
    x = get_ZB23(solution, tmin, tmax)
    pks = rcopy(R"""
cp_peaks = $(x) |>
  dplyr::select(all_of(c("time", $(parameter)))) |>
  astrochron::peak(plateau = FALSE, genplot = FALSE) |>
  dplyr::mutate(diff = Location - lead(Location)) |>
  tidyr::drop_na()
""")
    @info "identied peaks"

    return pks.diff
end

"rolling block bootstrap"
my_simple_wrapper = function(solution = 1, tmin = -1205e3, tmax = -1200e3;
                             b = 75, N = 999, parameter = "cp")
    x = get_ZB23(solution, tmin, tmax)
    pks = rcopy(R"""
cp_peaks = $(x) |>
  dplyr::select(all_of(c("time", $(parameter)))) |>
  astrochron::peak(plateau = FALSE, genplot = FALSE) |>
  dplyr::mutate(diff = Location - lead(Location)) |>
  tidyr::drop_na()
""")
    @info "identied peaks"
    megaboot = moving_block_bootstrap( pks.diff, mean; b = b, N = N )
    @info "booted"

    return megaboot
end

my_wrapper = function(solution = 1, fun = mean, tmin = -1205e3, tmax = -1200e3;
                      b = 75, N = 999, parameter = "cp")
    x = get_ZB23(solution, tmin, tmax)
    pks = rcopy(R"""
cp_peaks = $(x) |>
  dplyr::select(all_of(c("time", $(parameter)))) |>
  astrochron::peak(plateau = FALSE, genplot = FALSE) |>
  dplyr::mutate(diff = Location - lead(Location)) |>
  tidyr::drop_na()
""")
    @info "identied peaks"
    bt = my_boot(pks.diff, fun; b = b, N = N)
    @info "booted"
    return bt
end

wrapper = function(solution = 1, fun = mean, tmin = -1205e3, tmax = -1200e3)
    x = get_ZB23(solution, tmin, tmax)

    # create ETP with weights
    # 1.5, 1.2, 1.2 from Figure S12 caption
    etp_weights = [1.5, 1.2, 1.2]
    # uses StatsBase.zscore
    necc .= zscore(x.ecc)
    nobl .= zscore(x.epl)
    nprec .= zscore(x.cp)
    @. x.etp .= etp_weights[1] * necc + etp_weights[2] * nobl + etp_weights[3] * nprec
    @info "calculated ETP with weights $etp_weights"

    filter_freqs = DataFrame(
    target = ["p1", "p2",  "p", "o1", "o2", "o12", "o3", "e", "E"],
        flow =  [0.0653, 0.075, 0.065, 0.0415, 0.0472, 0.042, 0.057, 1/155, 1/440],
        fhigh = [0.07, 0.0785, 0.0785, 0.044, 0.0505, 0.0505, 0.06, #0.0594, # OR 0.06 for some!
                 1/75, 1/370
                 ]
    )

    window_size = 1e3
    cut_groups = tmin:window_size:tmax |> collect
    cut_groups[end] = cut_groups[end] + 1

R"""
my_peak <- function(data) {
    data |>
        dplyr::select(all_of(c("time", "filter"))) |>
        astrochron::peak(plateau = FALSE, genplot = FALSE, verbose = FALSE) |>
        dplyr::rename(peak_age = Location, peak_value = Peak_Value) |>
        dplyr::mutate(diff = peak_age - dplyr::lag(peak_age)) |>
        tidyr::drop_na()
}
"""

    pks = rcopy(R"""
cp_flt = $(x) |>
  # this is from my R package CretaceousConstraints
  bandpass_filter(frequencies = $(filter_freqs), x = time, y = etp) |>
  # taner_filter(frequencies = $(filter_freqs), x = time, y = etp, roll = 1e3, verbose = FALSE, genplot = FALSE) |>
  tidyr::nest(.by = "target") |>
  dplyr::mutate(pk = purrr::map(data, my_peak)) |>
  dplyr::select(-"data") |>
  tidyr::unnest(cols = "pk") |>
  mutate(grp = cut(peak_age, $(cut_groups)))
""")
    @info "filtered frequencies"
    @info "identied peaks"

    means = rcopy(R"""
cp_flt |>
   summarize(.by = c(grp, target),
             mean_age = mean(peak_age),
             mean_diff_1Myr = mean(diff),
             n = n()) |>
   mutate(solution = $(x.sol[1]))
""")
    # TODO: do something else so it become
    # for (i, gr), (j, target) in enumerate(pks.grp), enumerate(pks.target)
    #     means = bootstrap(mean, pks.diff, MaximumEntropySampling(999))
    # end

    @info "calculated means"
    return means
end

ecc_wrapper = function(solution = 1, fun = mean, tmin = -1250e3, tmax = -1200e3)
    x = get_ZB23(solution, tmin, tmax)

    # create ETP with weights
    # 1.5, 1.2, 1.2 from Figure S12 caption
    etp_weights = [1.5, 1.2, 1.2]
    # uses StatsBase.zscore
    necc = zscore(x.ecc)
    nobl = zscore(x.epl)
    nprec = zscore(x.cp)
    @. x.etp .= etp_weights[1] * necc + etp_weights[2] * nobl + etp_weights[3] * nprec
    @info "calculated ETP with weights $etp_weights"

    filter_freqs = DataFrame(
    target = ["p1", "p2",  "p", "o1", "o2", "o12", "o3", "e", "E"],
        flow =  [0.0653, 0.075, 0.065, 0.0415, 0.0472, 0.042, 0.057, 1/155, 1/440],
        fhigh = [0.07, 0.0785, 0.0785, 0.044, 0.0505, 0.0505, 0.06, #0.0594, # OR 0.06 for some!
                 1/75, 1/370]
    )

    window_size = 1e3
    cut_groups = tmin:window_size:tmax |> collect
    cut_groups[end] = cut_groups[end] + 1

R"""
my_peak <- function(data) {
    data |>
        dplyr::select(all_of(c("time", "filter"))) |>
        astrochron::peak(plateau = FALSE, genplot = FALSE, verbose = FALSE) |>
        dplyr::rename(peak_age = Location, peak_value = Peak_Value) |>
        dplyr::mutate(diff = peak_age - dplyr::lag(peak_age)) |>
        tidyr::drop_na()
}
"""

    pks = rcopy(R"""
cp_flt = $(x) |>
  # this is from my R package CretaceousConstraints
  bandpass_filter(frequencies = $(filter_freqs), x = time, y = etp) |>
  # taner_filter(frequencies = $(filter_freqs), x = time, y = etp, roll = 1e3, verbose = FALSE, genplot = FALSE) |>
  tidyr::nest(.by = "target") |>
  dplyr::mutate(pk = purrr::map(data, my_peak)) |>
  dplyr::select(-"data") |>
  tidyr::unnest(cols = "pk") |>
  mutate(grp = cut(peak_age, $(cut_groups)))
""")
    @info "filtered frequencies"
    @info "identied peaks"

    means = rcopy(R"""
cp_flt |>
   summarize(.by = c(grp, target),
             mean_age = mean(peak_age),
             mean_diff_1Myr = mean(diff),
             n = n()) |>
   mutate(solution = $(x.sol[1]))
""")
    # TODO: do something else so it become
    # for (i, gr), (j, target) in enumerate(pks.grp), enumerate(pks.target)
    #     means = bootstrap(mean, pks.diff, MaximumEntropySampling(999))
    # end

    @info "calculated means"
    return means
end


ecc_wrapper_julia = function(solution = 1,
                             fun = mean,
                             tmin = -1250e3, tmax = -1200e3
                             # tmin = -1205e3, tmax = -1200e3
                             )
    x = get_ZB23(solution, tmin, tmax)

    # create ETP with weights
    # 1.5, 1.2, 1.2 from Figure S12 caption
    etp_weights = [1.5, 1.2, 1.2]
    # uses StatsBase.zscore
    necc = zscore(x.ecc)
    nobl = zscore(x.epl)
    nprec = zscore(x.cp)
    @. x.etp .= etp_weights[1] * necc +
        etp_weights[2] * nobl +
        etp_weights[3] * nprec
    @info "calculated ETP with weights $etp_weights"

    Milankovitch_targets = Dict(
        :p1 => (0.0653, 0.07),
        :p2 => (0.075, 0.0785),
        :p => (0.065, 0.0785),
        :o1 => (0.0415, 0.044),
        :o2 => (0.0472, 0.0505),
        :o12 => (0.042, 0.0505),
        :o3 => (0.057, 0.0594),
        :e => (1/155, 1/75),
        :E => (1/440, 1/370)
    )

    # # using_a_dict = function()
    # filtered_targets = Dict{Symbol, Vector{Float64}}()
    # for (k, (flow, fhigh)) in Milankovitch_targets
    #     filtered_targets[k] = bandpass(x.etp, 0.4, flow, fhigh)
    # end
    #     # end
    # using_a_df = function()
    filtered_targets = DataFrame(etp = x.etp)
    for (name, (flow, fhigh)) in Milankovitch_targets
        filtered_targets[!, name] = bandpass(x.etp, 0.4, flow, fhigh)
    end
    df = stack(filtered_targets[!, Not(:etp)], view = true)
        # end
    # @btime using_a_dict()
    # # after first run, 995 ms
    # @btime using_a_df()
    # # 991 ms (sliiightly faster)
    @info "filtered"

    # work on grouped df
    peaks = combine(groupby(df, :variable),
                    :value => (z -> x.time[findmaxima(z).indices]) => :time)
    # append to df => just work with dicts for now
    # for (name, component) in filtered_targets
    #     x[!, Symbol(name)] = component
    # end
    # # TODO: reshaping is a bit slow, so could also not do it?
    # filt_long = stack(x[!, Not([:ecc, :inc, :epl, :cp, :sol])],
    #                   Not([:time, :etp]),
    #                   variable_name = :target, value_name = :amplitude)
    # peaks = Dict{Symbol, Vector{Float64}}()
    # peak_height = Dict{Symbol, Vector{Float64}}()
    # for (c) in enumerate(eachcol(filtered_targets[!,2:end]))
    #     @show names(c)
    #     fp = findmaxima(c)
    #     peaks[Milankovitch_targets.keys[i]]= x.time[fp.indices]
    # end

    @info "detected peaks"

    peaks = combine(groupby(peaks, :variable),
                    :time => (z -> z[1:end-1]) => :time, # identity but 1 fewer
                    :time => (z -> z[1:end-1] .- z[2:end]) => :duration,
                    :time => length => :npeaks)

    @info "calculated durations"

    block_size = 1000 # kyr = 1 Myr

    peaks.grp = floor.(Int, peaks.time / block_size)

    summ = combine(groupby(peaks, [:variable, :grp]),
                   :duration => mean => :avg_duration,
                   :npeaks => sum => :sum_peaks)

    sort!(summ, :variable)

    # grp = Dict{Symbol, Vector{String}}()
    # ns = Dict{Symbol, Vector{Int}}()
    # means = Dict{Symbol, Vector{Float64}}()
    # nmeans = length(cut_groups)-1

    # # TODO
    #     grp[k] = repeat([""],nmeans)
    #     means[k] = zeros(nmeans)
    #     ns[k] = zeros(Int, nmeans)
    #     for i in 1:nmeans
    #         # which ages fall within the cut group?
    #         ids = time .>= cut_groups[i] .&&
    #             time .< cut_groups[i+1]
    #         grp[k][i] = "($(cut_groups[i]),$(cut_groups[i+1])]"
    #         means[k][i] = mean(v[ids])
    #         ns[k].n[i] = length(v[ids])
    #     end
    # end

    @info "calculated means"

    summ.solution .= x.sol[1]
    # return (x.sol[1], peaks, means, ns)
    return(summ)
end
